# Utiliser l'image officielle Node.js avec une version spécifique
FROM node:14

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json vers le répertoire de travail
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet vers le répertoire de travail
COPY . .

# Exposer le port sur lequel votre application Node.js s'exécute
EXPOSE 1000

# Configuration de l'environnement pour la base de données MySQL
ENV DATABASE_URL="mysql://root:password@host.docker.internal:3306/store"

# Build de la base de données avec Prisma
RUN npx prisma generate

# Commande pour exécuter l'application
CMD [ "npx", "nodemon" ]


#apres
#1  docker build -t server-carhuber
#2  docker run -p 1000:1000 server-carhuer

